version: "3.9"
services:
  map-segmentation-backend:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./app.log:/var/log/app.log
      - ./best_epoch_pretrained_case_data.bin:/app/best_epoch.bin

# volumes:
#     - log
